const WORD_SPARK_WORDS = [
  { word: "serene", meaning: "平静的", example: "A serene morning makes it easier to begin." },
  { word: "glimpse", meaning: "一瞥", example: "She caught a glimpse of the idea." },
  { word: "thrive", meaning: "茁壮成长", example: "Small habits thrive with steady attention." },
  { word: "curious", meaning: "好奇的", example: "Stay curious when the answer feels close." },
  { word: "brisk", meaning: "轻快的", example: "A brisk walk cleared his thoughts." },
  { word: "linger", meaning: "逗留", example: "Let the question linger for a minute." },
  { word: "craft", meaning: "精心制作", example: "Craft the sentence until it feels clean." },
  { word: "vivid", meaning: "生动的", example: "A vivid example beats a vague rule." },
  { word: "steady", meaning: "稳定的", example: "Steady progress is still progress." },
  { word: "spark", meaning: "火花", example: "One word can spark a new direction." },
  { word: "focus", meaning: "专注", example: "Focus turns effort into shape." },
  { word: "gentle", meaning: "温和的", example: "A gentle reminder is easier to keep." },
  { word: "wander", meaning: "漫游", example: "Let your mind wander, then return." },
  { word: "bold", meaning: "大胆的", example: "Try the bold version first." },
  { word: "anchor", meaning: "锚点", example: "Use one clear anchor for the task." },
  { word: "polish", meaning: "打磨", example: "Polish the rough edge, not the whole stone." },
  { word: "brief", meaning: "简短的", example: "Keep the note brief and useful." },
  { word: "trace", meaning: "痕迹", example: "Trace the bug back to its first clue." },
  { word: "bloom", meaning: "开花", example: "Ideas bloom when they get room." },
  { word: "merge", meaning: "合并", example: "Merge similar thoughts before adding more." },
  { word: "pause", meaning: "暂停", example: "Pause before you answer too quickly." },
  { word: "revise", meaning: "修改", example: "Revise the plan after the first test." },
  { word: "signal", meaning: "信号", example: "Look for the signal inside the noise." },
  { word: "rhythm", meaning: "节奏", example: "Find a rhythm you can repeat." },
  { word: "clarity", meaning: "清晰", example: "Clarity arrives one choice at a time." },
  { word: "humble", meaning: "谦逊的", example: "A humble fix can save the day." },
  { word: "nimble", meaning: "灵活的", example: "Stay nimble when the page changes." },
  { word: "measure", meaning: "衡量", example: "Measure what actually changed." },
  { word: "delight", meaning: "愉悦", example: "A tiny detail can create delight." },
  { word: "resolve", meaning: "解决", example: "Resolve the doubt with a small test." },
  { word: "patient", meaning: "耐心的", example: "Be patient with the first draft." },
  { word: "insight", meaning: "洞察", example: "The insight was hiding in plain sight." },
  { word: "glow", meaning: "发光", example: "The screen had a soft glow." },
  { word: "restore", meaning: "恢复", example: "Restore your attention with a short break." },
  { word: "venture", meaning: "冒险尝试", example: "Venture beyond the first obvious answer." },
  { word: "thread", meaning: "线索", example: "Follow the thread through the code." },
  { word: "mellow", meaning: "柔和的", example: "A mellow tone made the message land." },
  { word: "stride", meaning: "大步前进", example: "Take one confident stride." },
  { word: "honest", meaning: "诚实的", example: "An honest status update helps everyone." },
  { word: "lift", meaning: "提升", example: "One clear example can lift the whole page." }
];
